import type { DataSource, MockDatabase, ValidationResponse } from '../../shared/types.js'

const now = new Date().toISOString()

export const defaultDataSources: DataSource[] = [
  {
    id: 'source-demo-industry',
    name: '饮料行业公开资料（模拟）',
    type: 'demo',
    entryUrl: 'https://demo.genki-lab.local/industry',
    crawlMethod: 'MockCollector 固定样本',
    keywords: ['饮料趋势', '低糖', 'Z世代'],
    schedule: '每周一 09:00（后续由妙搭触发）',
    enabled: true,
    collectionMode: 'demo',
    collectorType: 'mock',
    collectorConfig: { maxItems: 5 },
    lastSuccessAt: null,
    failureCount: 0,
    lastError: null,
    lastRunNewCount: 0,
    notes: '固定生成明确标记的 DEMO DATA，不代表真实网页采集。',
  },
  {
    id: 'source-rss-fsa-research',
    name: '英国食品标准局研究 RSS',
    type: 'rss',
    entryUrl: 'https://science.food.gov.uk/feed',
    crawlMethod: 'RSSCollector',
    keywords: ['food research', 'consumer', 'health', 'innovation'],
    schedule: '每日 08:30',
    enabled: true,
    collectionMode: 'live',
    collectorType: 'rss',
    collectorConfig: { maxItems: 12 },
    lastSuccessAt: null,
    failureCount: 0,
    lastError: null,
    lastRunNewCount: 0,
    notes: '英国食品标准局 Research and Evidence 公开 RSS；保留原文链接与机构归属。',
  },
  {
    id: 'source-brand-coca-media',
    name: 'The Coca-Cola Company 官方媒体中心',
    type: 'brand_news',
    entryUrl: 'https://www.coca-colacompany.com/media-center',
    crawlMethod: 'ConfigurableListCollector',
    keywords: ['beverage', 'innovation', 'flavor', 'zero sugar'],
    schedule: '每日 10:00',
    enabled: true,
    collectionMode: 'live',
    collectorType: 'configurable_list',
    collectorConfig: {
      maxItems: 5,
      itemSelector: '.cmp-teaser:has(a[href*="/media-center/"])',
      titleSelector: '.cmp-teaser__title, h2, h3',
      linkSelector: 'a[href*="/media-center/"]',
      summarySelector: '.cmp-teaser__description, p',
      contentSelector: '.tccc-timeline-details .cmp-text',
      dateSelector: 'time',
    },
    lastSuccessAt: null,
    failureCount: 0,
    lastError: null,
    lastRunNewCount: 0,
    notes: '品牌官网公开媒体中心；不登录、不绕过访问控制，仅以保守频率读取页面。',
  },
  {
    id: 'source-industry-qj-statistics',
    name: '政府公开饮料消费统计文章',
    type: 'industry_article',
    entryUrl: 'https://www.qj.gov.cn/html/2025/tjxx_0122/271335.html',
    crawlMethod: 'GenericArticleCollector',
    keywords: ['饮料类零售额', '消费增长', '市场'],
    schedule: '每周一 09:30',
    enabled: true,
    collectionMode: 'live',
    collectorType: 'generic_article',
    collectorConfig: {
      maxItems: 1,
      titleSelector: 'h1',
      contentSelector: '.view, .content, article, main, body',
      dateSelector: 'time, .date, .info',
    },
    lastSuccessAt: null,
    failureCount: 0,
    lastError: null,
    lastRunNewCount: 0,
    notes: '曲靖市政府公开统计文章，包含饮料类零售额公开数据；仅保存摘要和证据链接。',
  },
]

const validationResponses: ValidationResponse[] = [
  [5, '清透青绿', 5, 5, '5-6元', [], '青提自然、气泡细，适合下午。'],
  [4, '原料特写', 4, 4, '5-6元', [], '茉莉不要太重。'],
  [4, '清透青绿', 5, 4, '4-5元', ['价格偏高'], '通勤会考虑购买。'],
  [3, '场景人物', 4, 3, '4-5元', ['花香偏重'], '希望茶感更轻。'],
  [5, '清透青绿', 5, 5, '5-6元', [], '冰镇后会更有吸引力。'],
  [3, '原料特写', 3, 3, '4-5元', ['担心香精感'], '青提需要更真实。'],
  [4, '清透青绿', 4, 4, '5-6元', [], '包装很清爽。'],
  [2, '场景人物', 3, 2, '4-5元', ['代糖后味'], '不喜欢明显代糖味。'],
  [4, '原料特写', 4, 4, '5-6元', [], '细密气泡是加分项。'],
  [3, '清透青绿', 4, 3, '4-5元', ['口味寡淡'], '希望青提更鲜明。'],
].map(([flavorInterest, packagePreference, sceneMatch, purchaseIntent, priceAcceptance, rejectionReasons, openFeedback], index) => ({
  id: `validation-demo-${String(index + 1).padStart(2, '0')}`,
  productConceptId: index < 5 ? 'demo-qingti-jasmine-v1' : 'demo-qingti-jasmine-v2',
  flavorInterest: flavorInterest as number,
  packagePreference: packagePreference as string,
  sceneMatch: sceneMatch as number,
  purchaseIntent: purchaseIntent as number,
  priceAcceptance: priceAcceptance as string,
  rejectionReasons: rejectionReasons as string[],
  openFeedback: openFeedback as string,
  submittedAt: now,
  isDemo: true,
}))

export function createSeedDatabase(): MockDatabase {
  return {
    dataSources: defaultDataSources.map((source) => ({ ...source })),
    rawItems: [],
    trendSignals: [],
    productConcepts: [],
    validationResponses,
    jobRuns: [],
    aiBatches: [],
    aiAnalysisRecords: [],
    aiAnalysisRuns: [],
    aiResultImports: [],
    trendCandidates: [],
    evaluationRuns: [],
  }
}
